server/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  post '/auth/login', to: 'auth#create'
  put '/users', to: 'users#update'
  post 'articles/viewed', to: 'viewedposts#create'
  post '/user/subscription', to: 'subscriptions#create'
  get 'articles/recommendations', to: 'recommendations#show'
  resources :articles
  resources :users, except: [:new]
  resources :comments, only: [:create, :update, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :followers, only: [:create, :destroy]
  resources :followings, only: [:create, :destroy]
end

server/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

server/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_authentication
  def show
    @article = Article.find(params[:id])
    render json: {"article": @article, likes: @article.likes, comments: @article.comments}
  end

  def index
    @articles = Article.all
    article = []
    @articles.each do |obj|
    article << {"article": obj, "likes": obj.likes, "comments": obj.comments}
    end
    render json: article
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.user != @current_user
      return render json: {msg: "you are not author of article"}
    end
    if @article.update(params.require(:article).permit(:title, :description))
      render json: @article, status: :ok
    else
      render json: {errors: @article.errors.full_messages}
    end
  end
  
  protect_from_forgery with: :null_session # For APIs, we disable CSRF protection

  def create
    @article = Article.new(article_params)
    @article.user = @current_user
    if @article.save
      render json: @article, status: :created
    else
      render json: { errors: @article.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.user != @current_user
      return render json: {msg: "you are not author of article"}
    end
    if @article.destroy
      render json: {msg: "given article deleted succesfully"}, status: :ok
    else
      render json: {errors: @article.errors.full_messages}, status: :no_content
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :description, :topic)
  end

  def require_authentication
    header = request.headers['Authorization']
    token = header.split(' ').last if header

    begin
      decoded_token = JWT.decode(token, 'your_secret_key', true, algorithm: 'HS256')
      render json: {error: "invalid token"} if !decoded_token[0]['user_id']
      @current_user = User.find(decoded_token[0]['user_id'])
    rescue JWT::DecodeError
      render json: { error: header }, status: :unauthorized
    end
  end
  # config/application.rb or config/initializers/cors.rb
end

server/app/views/articles/edit.html.erb
<h1>Edit article</h1>

<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

server/app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

server/app/views/articles/new.html.erb
<h1>Create a new article</h1>

<% if @article.errors.any? %> 
  <h2>The following errors prevented the article from being saved</h2> 
  <ul> 
    <% @article.errors.full_messages.each do |msg| %> 
      <li><%= msg %></li> 
    <% end %> 
  </ul>
<% end %>

<%= form_with scope: :article, url: articles_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

server/app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>